# Generated by Django 5.2.5 on 2025-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_profile_dob_alter_profile_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightlog',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
