# Generated by Django 5.2.5 on 2025-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_weightlog_check_in_weightlog_check_in_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
