# Generated by Django 5.2.5 on 2025-09-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_profile_gender'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS weight_usermilestone;
                DROP TABLE IF EXISTS weight_milestone;
                ALTER TABLE weight_profile DROP COLUMN streaks;
                ALTER TABLE weight_profile DROP COLUMN streaks_from;
                ALTER TABLE weight_weightlog DROP COLUMN bmi;
            """,
            reverse_sql=migrations.RunSQL.noop,  # no reverse needed
        ),
    ]
