# Generated by Django 5.2.5 on 2025-09-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('bmi', 'BMI'), ('streak', 'Streak'), ('target', 'Target'), ('consistency', 'Consistency')], max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='streaks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streaks_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_on', models.DateField(auto_now_add=True)),
                ('displayed', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight.milestone')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight.profile')),
            ],
            options={
                'unique_together': {('profile', 'milestone')},
            },
        ),
    ]
