# Generated by Django 5.2.5 on 2025-09-28 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0007_milestone_profile_streaks_profile_streaks_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('avg_weight', models.FloatField()),
                ('change_from_last_week', models.FloatField(default=0.0)),
                ('bmi_status', models.CharField(max_length=20)),
                ('streak', models.IntegerField(default=0)),
                ('highlights', models.JSONField(blank=True, default=dict)),
                ('has_checked', models.BooleanField(default=False)),
                ('checked_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start', 'week_end')},
            },
        ),
    ]
