# Generated by Django 5.2.5 on 2026-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0009_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='daily_reminder_enabled',
            new_name='daily_log',
        ),
        migrations.AddField(
            model_name='settings',
            name='weekly_summary',
            field=models.BooleanField(default=False),
        ),
    ]
