# Generated by Django 5.2.5 on 2026-02-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0010_rename_daily_reminder_enabled_settings_daily_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='height_unit',
            field=models.CharField(choices=[('cms', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=5),
        ),
    ]
