# Generated by Django 5.2.5 on 2026-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0011_settings_height_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=5),
        ),
    ]
